---
- name: gather needed facts for template
  hosts: mysql:rabbitmq:keystone:glance:neutron-api:nova-controller

- name: Install nova compute on nodes
  hosts: nova-compute
  sudo: True
  gather_facts: True
  tasks:

    - debug: var= hostvars[inventory_hostname]
    - debug: var= "{{ hostvars[ansible_hostname]|find_ip(management_network) }}"
   
    - name: ensure /boot/vmlinuz is world-readable
      shell: chmod 0644 /boot/vmlinuz*

    - name: ensure nova-compute packages are installed
      apt: 
        pkg: "{{ item }}"
        state: latest 
        update_cache: yes 
        cache_valid_time: 600
      with_items:
        - "{{ nova_compute_package }}"
        - python-guestfs
      
    - name: ensure services are stopped
      service: 
        name: nova-compute 
        state: stopped

    - name: ensure nova.conf file is present
      template: 
        src: templates/etc/nova/nova.conf 
        dest: /etc/nova/nova.conf 
        owner: nova 
        group: nova 
        mode: 0600

    - name: update api-paste.ini from template
      template: 
        src: templates/etc/nova/api-paste.ini 
        dest: /etc/nova/api-paste.ini 
        owner: nova 
        group: nova 
        mode: 0600

    - name: ensure compute service is started and enabled
      service: 
        name: nova-compute 
        state: restarted 
        enabled: yes

