---
- name: Configure RabbitMQ server
  hosts: rabbitmq
  sudo: True
  gather_facts: False
  tasks:

    - name: ensure nova vhost is present
      rabbitmq_vhost: 
        name: /nova
        state: present

    - name: ensure nova user is present
      rabbitmq_user: 
        user: nova
        password: "{{ nova_rabbit_password }}" 
        vhost: /nova 
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present
        force: yes
