---
- name: gather glance host facts
  hosts: glance-api
  gather_facts: True
  sudo: False

- name: make sure glance is in keystone
  hosts: keystone 
  gather_facts: True
  sudo: False
  tasks:

    - name: create glance user in keystone
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ keystone_admin_token }}" 
        tenant: service 
        user: glance 
        password: "{{ glance_identity_password }}"

    - name: add glance user to the service tenant with the admin role
      keystone_user: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ keystone_admin_token }}" 
        tenant: service 
        user: glance 
        role: admin

    - name: add glance endpoint
      keystone_service: 
        endpoint: "{{ keystone_admin_url }}"
        token: "{{ keystone_admin_token }}"
        region: "{{ openstack_region }}"
        name: glance
        type: image
        description: "Image Service"
        public_url: "{{ glance_public_url }}"
        internal_url: "{{ glance_internal_url }}"
        admin_url: "{{ glance_admin_url }}"

